/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * 
 *
 * Created on 06-05-2011, 11:07:31 AM
 */

package controlcolas.vista.admin;

import controlcolas.control.ColaJpaController;
import controlcolas.modelo.Cola;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.Fmt;
import utilidades.Tabla;

/**
 *
 * @author Ramiro Duran
 */
//public class ColaVista extends javax.swing.JFrame {
public class GestionarColas extends javax.swing.JDialog {
    private ColaJpaController ctrlCola = new ColaJpaController();
    private Cola cola=null;
    private List<Cola> colaList;
    private int uIndex=0;
//    private String MODULO;
//    private Usuario USUARIO;

    //private int uIndex=0;
    /** Creates new form Vista */
    public GestionarColas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Fmt.initForm(this);
        
        colaList = ctrlCola.findColaEntities();
        if (colaList==null) colaList = ctrlCola.findColaEntities(0,1);
        if (!colaList.isEmpty() && colaList.size()>0)  {
            cola=colaList.get(0);
            uIndex=0;
        } 
        else cola=null;
        mostrarTabla();
        estadoEstable();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbPrimer = new javax.swing.JButton();
        jbAnterior = new javax.swing.JButton();
        jbSiguiente = new javax.swing.JButton();
        jbUltimo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlCola = new javax.swing.JLabel();
        jtfSigla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jtfNombre = new javax.swing.JTextField();
        jlCola1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Codificador de Colas");
        setMinimumSize(new java.awt.Dimension(470, 400));
        setResizable(false);

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNuevo);

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disk.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGuardar);

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar);

        jbCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/door_out.png"))); // NOI18N
        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrar);

        jbPrimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/first.png"))); // NOI18N
        jbPrimer.setText("Primer");
        jbPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrimerActionPerformed(evt);
            }
        });
        jPanel2.add(jbPrimer);

        jbAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/previous.png"))); // NOI18N
        jbAnterior.setText("Anterior");
        jbAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnteriorActionPerformed(evt);
            }
        });
        jPanel2.add(jbAnterior);

        jbSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/next.png"))); // NOI18N
        jbSiguiente.setText("Siguiente");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });
        jPanel2.add(jbSiguiente);

        jbUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/last.png"))); // NOI18N
        jbUltimo.setText("Ultimo");
        jbUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUltimoActionPerformed(evt);
            }
        });
        jPanel2.add(jbUltimo);

        jlCola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlCola.setText("Nombre Cola:");

        jtfSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSiglaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSiglaKeyTyped(evt);
            }
        });

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nombre de la Cola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTabla.getTableHeader().setReorderingAllowed(false);
        jtTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaMouseClicked(evt);
            }
        });
        jtTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabla);
        if (jtTabla.getColumnModel().getColumnCount() > 0) {
            jtTabla.getColumnModel().getColumn(0).setMinWidth(50);
            jtTabla.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jlCola1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlCola1.setText("Sigla:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCola)
                    .addComponent(jlCola1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCola1))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        if (!validacion()) {
            return;
        }
        
        if (jbGuardar.getToolTipText().equals("Guardar nuevo registro")) {
                cola = new Cola();
        } 
        cola.setSigla(jtfSigla.getText().toUpperCase());
        cola.setNombre(jtfNombre.getText().toUpperCase());        
        cola.setFichaActual(0);
        cola.setFichasEmitidas(0);
        try {
            if (jbGuardar.getToolTipText().equals("Guardar nuevo registro"))  {
                    ctrlCola.create(cola);
                    colaList.add(cola);
                    uIndex=colaList.size()-1;
            }
            else  {
                ctrlCola.edit(cola);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No es posible registrar o editar  el registro,\n puede existir un registro duplicado.");
        }
        mostrarTabla();        
        estadoEstable();

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        jbNuevo.setEnabled(false);
        jbGuardar.setEnabled(true);
        jbGuardar.setToolTipText("Guardar nuevo registro");
        jbEliminar.setEnabled(true);
        jbEliminar.setText("Cancelar");
        jbEliminar.setToolTipText("Cancelar registro");
        jbAnterior.setEnabled(false);
        jbSiguiente.setEnabled(false);
        jbPrimer.setEnabled(false);
        jbUltimo.setEnabled(false);
        
        jtfSigla.setEnabled(true);
        jtfNombre.setEnabled(true);
        jtfNombre.setText("");
        jtfSigla.setText("");
        jtfSigla.requestFocus();

    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if(jbEliminar.getText().equals("Cancelar")) {
            estadoEstable();
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar este registro?","Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            try {
                ctrlCola.destroy(cola.getId());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No es posible eliminar el registro");
            }
            colaList.remove(cola);
            uIndex = uIndex>0?uIndex-1:0;
            if (!colaList.isEmpty())  cola=colaList.get(uIndex);
            else cola=null;
        }
        mostrarTabla();
        estadoEstable();
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrimerActionPerformed
        // TODO add your handling code here:
        uIndex=0;
        if (!colaList.isEmpty()) cola=colaList.get(uIndex);
        else cola=null;
        estadoEstable();
    }//GEN-LAST:event_jbPrimerActionPerformed

    private void jbAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnteriorActionPerformed
        // TODO add your handling code here:
        uIndex = uIndex>0?uIndex-1:0;
        if (!colaList.isEmpty() && uIndex<colaList.size()) cola=colaList.get(uIndex);
        else cola=null;
        estadoEstable();
    }//GEN-LAST:event_jbAnteriorActionPerformed

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
        // TODO add your handling code here:
        uIndex = (uIndex < colaList.size()-1)?uIndex+1:uIndex;
        if (!colaList.isEmpty() && uIndex<colaList.size()) cola=colaList.get(uIndex);
        else cola=null;
        estadoEstable();
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void jbUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUltimoActionPerformed
        // TODO add your handling code here:
        if (!colaList.isEmpty()) {
            uIndex=colaList.size()-1;
            cola=colaList.get(uIndex);
        }
        else cola=null;
        estadoEstable();
    }//GEN-LAST:event_jbUltimoActionPerformed

    private void jtfSiglaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiglaKeyTyped
        // TODO add your handling code here:
        estadoModificacion();
    }//GEN-LAST:event_jtfSiglaKeyTyped

    private void jtfSiglaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiglaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar()==10) jbGuardar.doClick();
    }//GEN-LAST:event_jtfSiglaKeyReleased

    private void jtTablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTablaKeyReleased
        // TODO add your handling code here:
        jtTablaMouseClicked(null);
    }//GEN-LAST:event_jtTablaKeyReleased

    private void jtTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaMouseClicked
        // TODO add your handling code here:
        int k = jtTabla.getSelectedRow();
        if (k>=0 && k<colaList.size()) {
                uIndex=k;
                if (!colaList.isEmpty()) cola=colaList.get(uIndex);
                else cola=null;
        }
        estadoEstable();
    }//GEN-LAST:event_jtTablaMouseClicked

    private void jtfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreKeyReleased

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionarColas(null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnterior;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbPrimer;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JButton jbUltimo;
    private javax.swing.JLabel jlCola;
    private javax.swing.JLabel jlCola1;
    private javax.swing.JTable jtTabla;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfSigla;
    // End of variables declaration//GEN-END:variables

    private void estadoEstable() {
        jbNuevo.setEnabled(true);
        jbGuardar.setEnabled(false);
        jbEliminar.setText("Eliminar");
        jbEliminar.setToolTipText("Eliminar registro");
        jbEliminar.setEnabled(true);
        jbAnterior.setEnabled(true);
        jbSiguiente.setEnabled(true);
        jbPrimer.setEnabled(true);
        jbUltimo.setEnabled(true);

        if (cola!=null) {
                jtfSigla.setText(colaList.get(uIndex).getSigla());
                jtfNombre.setText(colaList.get(uIndex).getNombre());
        } else {
        
            jbEliminar.setEnabled(false);
            jbAnterior.setEnabled(false);
            jbSiguiente.setEnabled(false);
            jbPrimer.setEnabled(false);
            jbUltimo.setEnabled(false);

            jtfSigla.setEnabled(false);
            jtfNombre.setEnabled(false);
            jtfSigla.setText("");
            jtfNombre.setText("");
        }
        if(colaList.size()<=1) {
                jbAnterior.setEnabled(false);
                jbSiguiente.setEnabled(false);
                jbPrimer.setEnabled(false);
                jbUltimo.setEnabled(false);
        }
        if(uIndex == (colaList.size()-1)) {
                jbSiguiente.setEnabled(false);
                jbUltimo.setEnabled(false);
        }
        if(uIndex==0) {
                jbAnterior.setEnabled(false);
                jbPrimer.setEnabled(false);
            }
        if (!colaList.isEmpty() && uIndex>=0 && uIndex<jtTabla.getRowCount())
                jtTabla.setRowSelectionInterval(uIndex, uIndex);
        
    }
    

    private boolean validacion() {
        if (jtfSigla.getText().isEmpty() || jtfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre o la sigla del registro esta en blanco");
            jtfSigla.requestFocus();
            return false;
        }
        return true;
    }

    private void estadoModificacion() {
        if(jbNuevo.isEnabled()) {
            jbNuevo.setEnabled(false);
            jbGuardar.setEnabled(true);
            jbGuardar.setToolTipText("Guardar registro modificado");
            jbEliminar.setEnabled(true);
            jbEliminar.setText("Cancelar");
            jbEliminar.setToolTipText("Cancelar modificar registro");
            jbAnterior.setEnabled(false);
            jbSiguiente.setEnabled(false);
            jbPrimer.setEnabled(false);
            jbUltimo.setEnabled(false);            
        }
    }

    private void mostrarTabla() {

        Tabla.limpiarTabla(jtTabla);
        for(int i=0;i<colaList.size();i++) {
           ((DefaultTableModel) jtTabla.getModel()).addRow(new Object[]{
                    colaList.get(i).getSigla(),
                    colaList.get(i).getNombre()
                });
        }
       
    }

}
