/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import controlcolas.control.ColaJpaController;
import controlcolas.modelo.Cola;
import controlcolas.vista.admin.GestionarColas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.Fmt;
import utilidades.Tabla;

/**
 *
 * @author Franz
 */
public class Gestion_colas extends javax.swing.JDialog{
        JPanel panel_contenedor;
        private ColaJpaController ctrlCola = new ColaJpaController();
        private Cola cola=null;
        private List<Cola> colaList;
        private int uIndex=0;
        
        public Gestion_colas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Fmt.initForm(this);
 
        colaList = ctrlCola.findColaEntities();
        if (colaList==null) colaList = ctrlCola.findColaEntities(0,1);
        if (!colaList.isEmpty() && colaList.size()>0)  {
            cola=colaList.get(0);
            uIndex=0;
        } 
        else cola=null;
        cargar_tabla();
        estadoEstable();
    }

    /**
     * Creates new form Gestion_colas
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnNuevoCola = new javax.swing.JButton();
        btnEditarCola = new javax.swing.JButton();
        btnNuevoCajero2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 199, 120));
        setMaximumSize(new java.awt.Dimension(945, 600));
        setMinimumSize(new java.awt.Dimension(945, 600));
        setPreferredSize(new java.awt.Dimension(945, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 348));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 348));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 348));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 32, 64));
        jLabel1.setText("Gestionar colas");

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nombre de la cola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabla.setToolTipText("");
        jScrollPane2.setViewportView(jtTabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 80));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(9, 32, 64));
        jLabel2.setText("Colas");

        btnNuevoCola.setBackground(new java.awt.Color(5, 166, 121));
        btnNuevoCola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevoCola.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/doc_new_icon&32.png"))); // NOI18N
        btnNuevoCola.setText("Nuevo");
        btnNuevoCola.setContentAreaFilled(false);
        btnNuevoCola.setOpaque(true);
        btnNuevoCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoColaMouseClicked(evt);
            }
        });
        btnNuevoCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoColaActionPerformed(evt);
            }
        });

        btnEditarCola.setBackground(new java.awt.Color(246, 182, 4));
        btnEditarCola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarCola.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/doc_new_icon&32.png"))); // NOI18N
        btnEditarCola.setText("Modificar");
        btnEditarCola.setContentAreaFilled(false);
        btnEditarCola.setOpaque(true);
        btnEditarCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarColaMouseClicked(evt);
            }
        });
        btnEditarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarColaActionPerformed(evt);
            }
        });

        btnNuevoCajero2.setBackground(new java.awt.Color(201, 11, 51));
        btnNuevoCajero2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoCajero2.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCajero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/doc_new_icon&32.png"))); // NOI18N
        btnNuevoCajero2.setText("Eliminar");
        btnNuevoCajero2.setContentAreaFilled(false);
        btnNuevoCajero2.setOpaque(true);
        btnNuevoCajero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoCajero2MouseClicked(evt);
            }
        });
        btnNuevoCajero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCajero2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(btnNuevoCola, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarCola, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoCajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarCola, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(btnNuevoCajero2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(btnNuevoCola, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoColaMouseClicked
       Nueva_cola cola = new Nueva_cola();
        panel_contenedor.removeAll();
        panel_contenedor.add(cola);
        repaint();
        cola.setVisible(true);

    }//GEN-LAST:event_btnNuevoColaMouseClicked

    private void btnNuevoColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoColaActionPerformed
        Nueva_cola cola = new Nueva_cola();
        panel_contenedor.removeAll();
        panel_contenedor.add(cola);
        repaint();
        cola.setVisible(true);
    }//GEN-LAST:event_btnNuevoColaActionPerformed

    private void btnEditarColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarColaMouseClicked

    }//GEN-LAST:event_btnEditarColaMouseClicked

    private void btnEditarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarColaActionPerformed

    private void btnNuevoCajero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoCajero2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoCajero2MouseClicked

    private void btnNuevoCajero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCajero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoCajero2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCola;
    private javax.swing.JButton btnNuevoCajero2;
    private javax.swing.JButton btnNuevoCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtTabla;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gestion_colas(null,true).setVisible(true);
            }
        });
    }
    public void cargar_tabla(){
    Tabla.limpiarTabla(jtTabla);
    for(int i=0;i<colaList.size();i++) {
            ((DefaultTableModel) jtTabla.getModel()).addRow(new Object[]{
                colaList.get(i).getSigla(),
                colaList.get(i).getNombre()
            });
        }
    }
    private void estadoEstable() {
        btnEditarCola.setEnabled(true);
        btnNuevoCajero2.setEnabled(false);
        //jbEliminar.setText("Eliminar");
        //jbEliminar.setToolTipText("Eliminar registro");
        btnNuevoCola.setEnabled(true);
        //jbAnterior.setEnabled(true);
        //jbSiguiente.setEnabled(true);
        //jbPrimer.setEnabled(true);
        //jbUltimo.setEnabled(true);

        if (cola==null) {
                //jtfSigla.setText(colaList.get(uIndex).getSigla());
                //jtfNombre.setText(colaList.get(uIndex).getNombre());
        
        
            btnEditarCola.setEnabled(false);
            btnNuevoCajero2.setEnabled(false);
            btnNuevoCola.setEnabled(false);
        }
        if (!colaList.isEmpty() && uIndex>=0 && uIndex<jtTabla.getRowCount())
                jtTabla.setRowSelectionInterval(uIndex, uIndex);
    }
}
