/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author Franz
 */
public class Gestionar_cajas extends javax.swing.JPanel {

    /**
     * Creates new form Gestionar_cajas
     */
    JPanel panel_contenedor;
    public Gestionar_cajas() {
        initComponents();
        this.setSize(1126,700);
        this.setPreferredSize(new Dimension(1126,700));
        this.setBounds(0, 0, 1126,700);
        setVisible(false);
        cargar_tabla();
    }
    public Gestionar_cajas(JPanel panel_contenedor) {
        initComponents();
        this.setSize(1126,700);
        this.setPreferredSize(new Dimension(1126,700));
        this.setBounds(0, 0, 1126,700);
        setVisible(false);
        this.panel_contenedor=panel_contenedor;
        cargar_tabla();
    }
        public void cargar_tabla(){
        tabla1.setBackground(Color.WHITE);
        tabla1.getTableHeader().setBackground(new Color(0,153,102));
        tabla1.getTableHeader().setForeground(Color.WHITE);
        tabla1.getTableHeader().setOpaque(false);
        tabla1.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabla1.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabla1.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabla1.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabla1.getColumnModel().getColumn(4).setPreferredWidth(150);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnNuevoCajero = new javax.swing.JButton();
        btnNuevoCajero1 = new javax.swing.JButton();
        btnNuevoCaja = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 199, 120));
        setMaximumSize(new java.awt.Dimension(945, 600));
        setMinimumSize(new java.awt.Dimension(945, 600));
        setPreferredSize(new java.awt.Dimension(945, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 348));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 348));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 348));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Maria Cortez", null, null, "Activo"},
                {"2", "Sara Torrez", null, null, "Activo"},
                {"4", "Mónica Llanos", null, null, "Activo"},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha actual", "Atendidos", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 32, 64));
        jLabel1.setText("Gestionar cajas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(323, 323, 323))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 80));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(9, 32, 64));
        jLabel2.setText("Cajas");

        btnNuevoCajero.setBackground(new java.awt.Color(246, 182, 4));
        btnNuevoCajero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoCajero.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/doc_new_icon&32.png"))); // NOI18N
        btnNuevoCajero.setText("Modificar");
        btnNuevoCajero.setContentAreaFilled(false);
        btnNuevoCajero.setOpaque(true);
        btnNuevoCajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoCajeroMouseClicked(evt);
            }
        });
        btnNuevoCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCajeroActionPerformed(evt);
            }
        });

        btnNuevoCajero1.setBackground(new java.awt.Color(201, 11, 51));
        btnNuevoCajero1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoCajero1.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCajero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/doc_new_icon&32.png"))); // NOI18N
        btnNuevoCajero1.setText("Eliminar");
        btnNuevoCajero1.setContentAreaFilled(false);
        btnNuevoCajero1.setOpaque(true);
        btnNuevoCajero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoCajero1MouseClicked(evt);
            }
        });
        btnNuevoCajero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCajero1ActionPerformed(evt);
            }
        });

        btnNuevoCaja.setBackground(new java.awt.Color(5, 166, 121));
        btnNuevoCaja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNuevoCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/doc_new_icon&32.png"))); // NOI18N
        btnNuevoCaja.setText("Nuevo");
        btnNuevoCaja.setContentAreaFilled(false);
        btnNuevoCaja.setOpaque(true);
        btnNuevoCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoCajaMouseClicked(evt);
            }
        });
        btnNuevoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(btnNuevoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoCajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCajero, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnNuevoCajero1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnNuevoCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoCajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoCajeroMouseClicked
        
    }//GEN-LAST:event_btnNuevoCajeroMouseClicked

    private void btnNuevoCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoCajeroActionPerformed

    private void btnNuevoCajero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoCajero1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoCajero1MouseClicked

    private void btnNuevoCajero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCajero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoCajero1ActionPerformed

    private void btnNuevoCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoCajaMouseClicked
        // TODO add your handling code here:
        Crear_cajas cajas = new Crear_cajas();
        panel_contenedor.removeAll();
        panel_contenedor.add(cajas);
        cajas.setVisible(true);
    }//GEN-LAST:event_btnNuevoCajaMouseClicked

    private void btnNuevoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCajaActionPerformed
        // TODO add your handling code here:
        Crear_cajas cajas = new Crear_cajas();
        panel_contenedor.removeAll();
        panel_contenedor.add(cajas);
        cajas.setVisible(true);
    }//GEN-LAST:event_btnNuevoCajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoCaja;
    private javax.swing.JButton btnNuevoCajero;
    private javax.swing.JButton btnNuevoCajero1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
