/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author Franz
 */
public class Nueva_cola extends javax.swing.JPanel {

    /**
     * Creates new form Nueva_cola
     */
    JPanel panel_contenedor;
    public Nueva_cola() {
        initComponents();
        Nueva_cola.this.setSize(945,636);
        Nueva_cola.this.setPreferredSize(new Dimension(945,636));
        Nueva_cola.this.setBounds(0, 0, 945,636);
        setVisible(false);
    }
    public Nueva_cola(JPanel panel_contenedor) {
        initComponents();
        this.panel_contenedor=panel_contenedor;
        Nueva_cola.this.setSize(panel_contenedor.getSize());
        Nueva_cola.this.setPreferredSize(panel_contenedor.getSize());
        Nueva_cola.this.setBounds(0, 0, panel_contenedor.getSize().width,panel_contenedor.getSize().height);
        setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldIcono1 = new mitextfieldicono.TextFieldIcono();
        jLabel4 = new javax.swing.JLabel();
        textFieldIcono2 = new mitextfieldicono.TextFieldIcono();
        jLabel5 = new javax.swing.JLabel();
        textFieldIcono3 = new mitextfieldicono.TextFieldIcono();
        jLabel6 = new javax.swing.JLabel();
        textFieldIcono4 = new mitextfieldicono.TextFieldIcono();
        jLabel7 = new javax.swing.JLabel();
        textFieldIcono5 = new mitextfieldicono.TextFieldIcono();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 199, 120));
        setMaximumSize(new java.awt.Dimension(945, 700));
        setMinimumSize(new java.awt.Dimension(945, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 650));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 32, 64));
        jLabel1.setText("Ingreso Colas");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 32, 64));
        jLabel3.setText("Id(*):");

        textFieldIcono1.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono1.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono1.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono1.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono1.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono1.setDimension_panel(new java.awt.Dimension(480, 35));
        textFieldIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 32, 64));
        jLabel4.setText("Sigla(*):");

        textFieldIcono2.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono2.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono2.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono2.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono2.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono2.setDimension_panel(new java.awt.Dimension(480, 35));
        textFieldIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(9, 32, 64));
        jLabel5.setText("Nombre(*):");

        textFieldIcono3.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono3.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono3.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono3.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono3.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono3.setDimension_panel(new java.awt.Dimension(480, 35));
        textFieldIcono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(9, 32, 64));
        jLabel6.setText("Fichas emitidas(*):");

        textFieldIcono4.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono4.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono4.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono4.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono4.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono4.setDimension_panel(new java.awt.Dimension(480, 35));
        textFieldIcono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(9, 32, 64));
        jLabel7.setText("Ficha actual(*):");

        textFieldIcono5.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono5.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono5.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono5.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono5.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono5.setDimension_panel(new java.awt.Dimension(480, 35));
        textFieldIcono5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Bodoni MT", 0, 30)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/cancel_icon&32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 102, 255));
        btnGuardar.setFont(new java.awt.Font("Bodoni MT", 0, 30)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white/png/save_icon&32.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setOpaque(true);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(textFieldIcono5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(textFieldIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldIcono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldIcono4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIcono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIcono4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIcono5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //  jp_clientes=new JPClientes(panel_contenedor);
        panel_contenedor.removeAll();
        //this.panel_contenedor.add(jp_clientes);
        //jp_clientes.setVisible(true);
        repaint();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private mitextfieldicono.TextFieldIcono textFieldIcono1;
    private mitextfieldicono.TextFieldIcono textFieldIcono2;
    private mitextfieldicono.TextFieldIcono textFieldIcono3;
    private mitextfieldicono.TextFieldIcono textFieldIcono4;
    private mitextfieldicono.TextFieldIcono textFieldIcono5;
    // End of variables declaration//GEN-END:variables
}
