/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JPanel;

/**
 *
 * @author Franz
 */
public class Visor_de_atencion extends javax.swing.JPanel {
    Frame parent;
    JPanel panel_contenedor;
    public Visor_de_atencion() {
        initComponents();
        Visor_de_atencion.this.setSize(1330,710);
        Visor_de_atencion.this.setPreferredSize(new Dimension(1126,700));
        Visor_de_atencion.this.setBounds(0, 0, 1126,700);
        setVisible(false);
    }
    public Visor_de_atencion(JPanel panel_contenedor) {
        initComponents();
        Visor_de_atencion.this.setSize(1330,710);
        Visor_de_atencion.this.setPreferredSize(new Dimension(1126,700));
        Visor_de_atencion.this.setBounds(0, 0, 1126,700);
        setVisible(false);
        this.panel_contenedor=panel_contenedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldIcono1 = new mitextfieldicono.TextFieldIcono();
        jLabel3 = new javax.swing.JLabel();
        textFieldIcono2 = new mitextfieldicono.TextFieldIcono();
        jLabel4 = new javax.swing.JLabel();
        textFieldIcono3 = new mitextfieldicono.TextFieldIcono();
        jLabel5 = new javax.swing.JLabel();
        textFieldIcono4 = new mitextfieldicono.TextFieldIcono();
        jLabel6 = new javax.swing.JLabel();
        textFieldIcono5 = new mitextfieldicono.TextFieldIcono();
        jLabel7 = new javax.swing.JLabel();
        textFieldIcono6 = new mitextfieldicono.TextFieldIcono();
        jLabel8 = new javax.swing.JLabel();
        buttonModeloA1 = new mibuttonmodeloa.ButtonModeloA();
        buttonModeloA3 = new mibuttonmodeloa.ButtonModeloA();
        btnAtender = new mibuttonmodeloa.ButtonModeloA();
        btnAtender1 = new mibuttonmodeloa.ButtonModeloA();
        jLabel9 = new javax.swing.JLabel();
        textFieldIcono7 = new mitextfieldicono.TextFieldIcono();
        textFieldIcono8 = new mitextfieldicono.TextFieldIcono();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 199, 120));
        setMaximumSize(new java.awt.Dimension(945, 700));
        setMinimumSize(new java.awt.Dimension(945, 700));
        setPreferredSize(new java.awt.Dimension(945, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 650));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 32, 64));
        jLabel1.setText("Atención Turnos");

        textFieldIcono1.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono1.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono1.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono1.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono1.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono1.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono1.setText("PEDIDO POR DEFECTO");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 32, 64));
        jLabel3.setText("Pedido actual:");

        textFieldIcono2.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono2.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono2.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono2.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono2.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono2.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono2.setText("C-0001");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 32, 64));
        jLabel4.setText("Turno actual:");

        textFieldIcono3.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono3.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono3.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono3.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono3.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono3.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono3.setText("EN ESPERA");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(9, 32, 64));
        jLabel5.setText("Estado turno actual:");

        textFieldIcono4.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono4.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono4.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono4.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono4.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono4.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono4.setText("3");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(9, 32, 64));
        jLabel6.setText("Turno espera:");

        textFieldIcono5.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono5.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono5.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono5.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono5.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono5.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono5.setText("0");

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(9, 32, 64));
        jLabel7.setText("Turnos atendidos:");

        textFieldIcono6.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono6.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono6.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono6.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono6.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono6.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono6.setText("0");

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 32, 64));
        jLabel8.setText("Turnos anulados:");

        buttonModeloA1.setColor_icono_normal(new java.awt.Color(204, 102, 0));
        buttonModeloA1.setColor_normal(new java.awt.Color(255, 153, 0));
        buttonModeloA1.setDimension_boton(new java.awt.Dimension(250, 100));
        buttonModeloA1.setDimension_icono(new java.awt.Dimension(100, 100));
        buttonModeloA1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonModeloA1.setFuente_texto(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonModeloA1.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/cancel_icon&48.png"))); // NOI18N
        buttonModeloA1.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/cancel_icon&48.png"))); // NOI18N
        buttonModeloA1.setTexto_boton("FINALIZAR");

        buttonModeloA3.setColor_icono_normal(new java.awt.Color(0, 102, 102));
        buttonModeloA3.setColor_normal(new java.awt.Color(0, 153, 153));
        buttonModeloA3.setDimension_boton(new java.awt.Dimension(250, 100));
        buttonModeloA3.setDimension_icono(new java.awt.Dimension(100, 100));
        buttonModeloA3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonModeloA3.setFuente_texto(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonModeloA3.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/phone_2_icon&48.png"))); // NOI18N
        buttonModeloA3.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/phone_2_icon&48.png"))); // NOI18N
        buttonModeloA3.setTexto_boton("LLAMAR");

        btnAtender.setColor_hover(new java.awt.Color(12, 201, 169));
        btnAtender.setColor_icono_hover(new java.awt.Color(25, 155, 133));
        btnAtender.setColor_icono_normal(new java.awt.Color(25, 155, 133));
        btnAtender.setColor_icono_pressed(new java.awt.Color(25, 155, 133));
        btnAtender.setColor_normal(new java.awt.Color(12, 201, 169));
        btnAtender.setColor_pressed(new java.awt.Color(12, 201, 169));
        btnAtender.setDimension_boton(new java.awt.Dimension(250, 100));
        btnAtender.setDimension_icono(new java.awt.Dimension(100, 100));
        btnAtender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtender.setFuente_texto(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtender.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/arrow_two_head_2_icon&48.png"))); // NOI18N
        btnAtender.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/arrow_two_head_2_icon&48.png"))); // NOI18N
        btnAtender.setTexto_boton("<html><center>TRANSFERIR<br> CLIENTE</center></html>");
        btnAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtenderMouseClicked(evt);
            }
        });

        btnAtender1.setColor_hover(new java.awt.Color(0, 153, 51));
        btnAtender1.setColor_icono_hover(new java.awt.Color(0, 122, 71));
        btnAtender1.setColor_icono_normal(new java.awt.Color(0, 102, 51));
        btnAtender1.setColor_icono_pressed(new java.awt.Color(0, 102, 51));
        btnAtender1.setColor_normal(new java.awt.Color(0, 153, 51));
        btnAtender1.setColor_pressed(new java.awt.Color(0, 153, 51));
        btnAtender1.setDimension_boton(new java.awt.Dimension(250, 100));
        btnAtender1.setDimension_icono(new java.awt.Dimension(100, 100));
        btnAtender1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtender1.setFuente_texto(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtender1.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/hand_pro_icon&48.png"))); // NOI18N
        btnAtender1.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/hand_pro_icon&48.png"))); // NOI18N
        btnAtender1.setTexto_boton("ATENDER");
        btnAtender1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtender1MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(9, 32, 64));
        jLabel9.setText("Cajero(a):");

        textFieldIcono7.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono7.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono7.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono7.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono7.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono7.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono7.setText("Maria Sanchez");

        textFieldIcono8.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIcono8.setColor_border(new java.awt.Color(153, 153, 153));
        textFieldIcono8.setColor_fondo(new java.awt.Color(204, 204, 204));
        textFieldIcono8.setColor_texto(new java.awt.Color(102, 102, 102));
        textFieldIcono8.setDimension_boton(new java.awt.Dimension(33, 33));
        textFieldIcono8.setDimension_panel(new java.awt.Dimension(300, 35));
        textFieldIcono8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black/png/cog_icon&16.png"))); // NOI18N
        textFieldIcono8.setText("1");

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(9, 32, 64));
        jLabel10.setText("Caja:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldIcono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldIcono4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldIcono5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(textFieldIcono6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtender1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldIcono7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(buttonModeloA3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonModeloA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(textFieldIcono8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldIcono8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldIcono7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textFieldIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonModeloA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModeloA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldIcono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAtender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldIcono4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldIcono5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldIcono6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAtender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderMouseClicked
        
    }//GEN-LAST:event_btnAtenderMouseClicked

    private void btnAtender1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtender1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtender1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mibuttonmodeloa.ButtonModeloA btnAtender;
    private mibuttonmodeloa.ButtonModeloA btnAtender1;
    private mibuttonmodeloa.ButtonModeloA buttonModeloA1;
    private mibuttonmodeloa.ButtonModeloA buttonModeloA3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private mitextfieldicono.TextFieldIcono textFieldIcono1;
    private mitextfieldicono.TextFieldIcono textFieldIcono2;
    private mitextfieldicono.TextFieldIcono textFieldIcono3;
    private mitextfieldicono.TextFieldIcono textFieldIcono4;
    private mitextfieldicono.TextFieldIcono textFieldIcono5;
    private mitextfieldicono.TextFieldIcono textFieldIcono6;
    private mitextfieldicono.TextFieldIcono textFieldIcono7;
    private mitextfieldicono.TextFieldIcono textFieldIcono8;
    // End of variables declaration//GEN-END:variables
}
