/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlcolas.vista.cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.Fmt;
import utilidades.Tabla;
import controlcolas.control.ColaJpaController;
import controlcolas.control.FichaJpaController;
import controlcolas.modelo.Cola;
import controlcolas.modelo.Ficha;
import java.util.List;

/**
 *
 * @author Franz
 */
public class ObtenerFicha_cola extends javax.swing.JPanel {
    private FichaJpaController ctrlFicha = new FichaJpaController();
    private Ficha ficha=null;
    private List<Ficha> fichaList;
    private int uIndex=0;
    /**
     * Creates new form ObtenerFicha_cola
     */
    public ObtenerFicha_cola() {
        initComponents();
        
        fichaList = ctrlFicha.findFichaEntities();
        if (fichaList==null) fichaList = ctrlFicha.findFichaEntities(0,1);
        if (!fichaList.isEmpty() && fichaList.size()>0)  {
            ficha=fichaList.get(0);
            uIndex=0;
        } 
        else ficha=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTE = new mibuttonmodeloa.ButtonModeloA();
        btnDP = new mibuttonmodeloa.ButtonModeloA();
        btnCN = new mibuttonmodeloa.ButtonModeloA();

        setBackground(new java.awt.Color(242, 199, 120));
        setForeground(new java.awt.Color(242, 199, 120));
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));

        jPanel1.setBackground(new java.awt.Color(9, 32, 64));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 150));
        jPanel1.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OBTENER FICHAS");
        jLabel1.setAlignmentX(288.0F);
        jLabel1.setAlignmentY(43.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(384, 65));
        jLabel1.setMinimumSize(new java.awt.Dimension(384, 65));
        jLabel1.setPreferredSize(new java.awt.Dimension(384, 65));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnTE.setColor_hover(new java.awt.Color(2, 74, 89));
        btnTE.setColor_icono_hover(new java.awt.Color(9, 32, 64));
        btnTE.setColor_icono_normal(new java.awt.Color(9, 32, 64));
        btnTE.setColor_icono_pressed(new java.awt.Color(9, 32, 64));
        btnTE.setColor_normal(new java.awt.Color(2, 74, 89));
        btnTE.setColor_pressed(new java.awt.Color(2, 74, 89));
        btnTE.setDimension_boton(new java.awt.Dimension(300, 100));
        btnTE.setDimension_icono(new java.awt.Dimension(100, 100));
        btnTE.setDoubleBuffered(false);
        btnTE.setFuente_texto(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnTE.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/users_icon&48.png"))); // NOI18N
        btnTE.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/users_icon&48.png"))); // NOI18N
        btnTE.setTexto_boton("Cliente tercera edad");
        btnTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTEMouseClicked(evt);
            }
        });

        btnDP.setColor_hover(new java.awt.Color(2, 74, 89));
        btnDP.setColor_icono_hover(new java.awt.Color(9, 32, 64));
        btnDP.setColor_icono_normal(new java.awt.Color(9, 32, 64));
        btnDP.setColor_icono_pressed(new java.awt.Color(9, 32, 64));
        btnDP.setColor_normal(new java.awt.Color(2, 74, 89));
        btnDP.setColor_pressed(new java.awt.Color(2, 74, 89));
        btnDP.setDimension_boton(new java.awt.Dimension(300, 100));
        btnDP.setDimension_icono(new java.awt.Dimension(100, 100));
        btnDP.setDoubleBuffered(false);
        btnDP.setFuente_texto(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDP.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/users_icon&48.png"))); // NOI18N
        btnDP.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/users_icon&48.png"))); // NOI18N
        btnDP.setTexto_boton("Cliente con capacidad diferente");
        btnDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDPMouseClicked(evt);
            }
        });

        btnCN.setColor_hover(new java.awt.Color(2, 74, 89));
        btnCN.setColor_icono_hover(new java.awt.Color(9, 32, 64));
        btnCN.setColor_icono_normal(new java.awt.Color(9, 32, 64));
        btnCN.setColor_icono_pressed(new java.awt.Color(9, 32, 64));
        btnCN.setColor_normal(new java.awt.Color(2, 74, 89));
        btnCN.setColor_pressed(new java.awt.Color(2, 74, 89));
        btnCN.setDimension_boton(new java.awt.Dimension(300, 100));
        btnCN.setDimension_icono(new java.awt.Dimension(100, 100));
        btnCN.setDoubleBuffered(false);
        btnCN.setFuente_texto(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCN.setIcono_hover(new javax.swing.ImageIcon(getClass().getResource("/white/png/users_icon&48.png"))); // NOI18N
        btnCN.setIcono_normal(new javax.swing.ImageIcon(getClass().getResource("/white/png/users_icon&48.png"))); // NOI18N
        btnCN.setTexto_boton("Cliente normal");
        btnCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCNMouseClicked

    private void btnTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTEMouseClicked

    private void btnDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mibuttonmodeloa.ButtonModeloA btnCN;
    private mibuttonmodeloa.ButtonModeloA btnDP;
    private mibuttonmodeloa.ButtonModeloA btnTE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
